---
title: "Cover Letter"
---

Please consider the attached paper, “Improving Functionalist Arguments”, for publication in the American Journal of Sociology.

In this paper we argue that sociologist's avoidance of "functions" is a major hindrance for sociological theory. This avoidance is unfortunate, since functional arguments provide a provide a kind of explanatory depth that is hard to obtain elsewhere. 

As such, this article has two goals. The first is disambiguation. What does it mean to attribute a function to something? We answer this question by elaborating a distinction between proper functions (responding to *why-is-it-there* questions) and role functions (responding to *how-does-it-work* questions). The second is to introduce a typology of functional arguments that builds upon this distinction. This allows us to recast “functionalism” as a set of general explanatory strategies and not as a substantive theory about society. Importantly, these forms of argument are not burdened by the weaknesses associated with the discredited organicist framework many sociologists have in mind when they think of “functionalism.” Instead of trying to eliminate all traces of “function talk” from sociology, we should be more explicit about the functional ascriptions we do make. This framework enables us to better evaluate, challenge, and improve upon much of the sociological research that currently relies on these forms of argument.

Functionalist arguments should not be considered taboo and sociologists should be able to make them, if that's what they want, without ever feeling obligated to talk about Talcott Parsons.

We believe this is an important contribution to sociological theory and that readers of this journal will be interested in the arguments laid out here.

Wordcount. 16,736 words
