---
title: "Improving Functionalist Arguments"
bibliography: references.bib
editor:
  render-on-save: true
---

\noindent Contemporary sociology finds itself in an awkward position. Despite having declared the death of functionalism, some form of functionalist argument still remains cryptically present in much substantive research. We argue that this inability to talk plainly about functions is a major hindrance for theory building in the discipline. As such, this article has two goals. The first is disambiguation. What does it mean to attribute a function to something? We answer this question by elaborating a distinction between proper functions (responding to *why-is-it-there* questions) and role functions (responding to *how-does-it-work* questions). The second is to introduce a typology of functional arguments that builds upon this distinction. This allows us to recast “functionalism” as a set of general explanatory strategies and not as a substantive theory about society. Importantly, these forms of argument are not burdened by the weaknesses associated with the discredited organicist framework most sociologists have in mind when they think of “functionalism.” Instead of trying to eliminate all traces of “function talk” from sociology, we should be more explicit about the functional ascriptions we do make. This framework enables us to better evaluate, challenge, and improve upon much of the sociological research that currently relies on these forms of argument.

\newpage

\epigraph{\textit{My apologies to the accidental for calling it necessary. However, apologies to necessity if I happen to be wrong.}}{\textit{— Wisława Szymborska}}

# Introduction

Sociologists have a fraught relationship with functionalist arguments. Many avoid using the word “functionalism” due to its association with defunct grand theories about society [e.g., @parsons_social_1951]. Others quickly point out that functionalist explanations have a track record of circular reasoning and illegitimate forms of teleological argument [@hempel_aspects_1965; @merton_social_1968; @elster_explaining_1983].[^1] If we were to trust oral tradition, then everything worth saying about functionalist arguments has already been said. However, despite claims to the contrary, some form of functionalist argument remains present in much substantive research without being explicitly recognized as such. This inability to talk transparently about functions is a major hindrance to sociological theory.

[^1]: Here, the word teleological is used to denote *purposive*, *goal-directed*, or *end-seeking* phenomena. An illegitimate teleology in sociology posits that some “purpose” or “goal” is driving human behavior when such is not the case.

We argue that functionalist arguments, by way of a set of general and recognizable explanatory strategies, provide a kind of explanatory depth that is hard to obtain elsewhere. These forms of argument should be distinguished from various functional*isms* or substantive theories about society. Our proposal is not committed to old-fashioned functionalism in sociology, nor to any contemporary theoretical system or research program. Nevertheless, it does have a substantive payoff. At a minimum, it is useful for the purposes of disambiguation, since the word “function” means very different things depending on the form of argument in which it is embedded. More importantly, making these forms of argument explicit will help us improve how we build and evaluate theories that rely on functional ascription to some degree.

The word “function” has many common uses that are not relevant here. Most often it is used in a mathematical sense to describe the relationship between variables or the mappings between sets. There is also a widespread tendency among researchers to use “function” as a synonym for effect, outcome, or consequence. Other times the word “function” is further qualified to describe only useful effects or beneficial consequences. However, none of these uses add any explanatory depth. Instead, we begin by distinguishing between *proper functions* and *role functions*, a well-established practice among philosophers. Each plays an important role in answering two different kinds of questions. Roughly speaking, proper functions are tied to *why-is-it-there* questions, whereas role functions are tied to *how-does-it-work* questions [@wright_functions_1973; @cummins_functional_1975; @garson_how_2018].[^2]

[^2]: This distinction is sometimes discussed in terms of the difference between *etiological* and *systemic* (or *constitutive)* aspects of explanations [@salmon_scientific_1984, 275; @craver_role_2001, 68-70]. For an introduction to this discussion among philosophers we recommend the articles compiled by @allen_natures_1998, as well as the more recent discussions contained provided in @craver_functions_2013 and @garson_how_2018.

Consider the following generic claim: $X$ *has a function* $F$ *if and only if* $X$ *is there because it does* $F$. This is the general scheme for an argument about *proper functions*. It can be applied to many things. For example, $X$ might be a trait, a belief, a behavior, a ritual, an artifact, an organization, a norm, a rule, and so on. Meanwhile $F$ is an activity or an “effect” that is typically characterized as being useful or beneficial (an adaptation). For example, $F$ may have the consequence of “bringing upon a reward,” “increasing the average fitness of a population,” or “solving a recurrent problem.” The difficulty with this general form of teleological argument is that it implies a type of backwards causality in which the existence and form of $X$ seems to be explained by its effects, rather than by its antecedent or “efficient” causes. To get around this problem, philosophers have further stipulated that all proper functions must be grounded historically. That is, we need an account of some *selection* or *reinforcement* process that explains how $F$ is able to account for the differential reproduction (or differential retention) of $X$*’*s kind over time. This is why the concept of a proper function is nowadays synonymous with the notion of a “selected effect” [@neander_functions_1991; @garson_generalized_2017].[^3]

[^3]: Earlier accounts of functional explanation suggested that statements of the form *“*$X$ has the function $F$*”* could be translated as *“*$X$ is a necessary condition for $F$*.”* These are statements about *logical necessities* [@nagel_structure_1961]. The implication being that functional ascription could be construed as deductive enterprise. In response, @hempel_aspects_1965 [310] argued that this kind of argument is non-explanatory since it is often a mistake to infer the origins of some $X$ by examining its consequences rather than the actual processes that brought it about. This view of functional explanations as providing statements about necessary conditions is conspicuously absent in contemporary philosophical discussions about function. Consequently, we do not go into further detail.

Unlike proper functions, role functions are not historical effects and they are not meant to explain *why* $X$ is there. Consider a knife that has been repurposed to tighten loose screws. This is now its role function. But this function is not the reason why this knife came into existence, nor is it the reason why knives in general have continued to be reproduced over time. Also, this knife could easily acquire a new role function in the hands of a different person (e.g., a weapon). And since we can imagine various contexts in which the same $X$ will have a different $F$, the ascription of role functions is then a matter of perspective [@craver_functions_2013]. More importantly, role functions are key in explanations that look “inside” some phenomenon in order to uncover the “nuts and bolts” responsible for its behavior. The idea is that we can answer *how-does-it-work* questions by understanding how the role functions of various “parts” are organized together to do something that none of them could do in isolation [@machamer_thinking_2000; @craver_role_2001].

The idea that there should be an analytical separation between proper functions and role functions has not always been embraced in sociology. This conflation becomes an important source of confusion because the very meaning of the word “function” depends on our explanatory goal, even when role functions and proper functions happen to coincide [@godfrey-smith_functions_1993, 345]. As a result, most sociologists conflate the two main forms of functional argument. This is surprising given that Émile Durkheim himself advocated explicitly for a strict separation between *how*-questions and *why*-questions: “when one undertakes to explain a social phenomenon, the efficient cause which produces it and the function it fulfills must be investigated separately” [@durkheim_rules_1982, 81]. Durkheim placed role functions at the center of his arguments about how the division of labor generated novel kinds of organic solidarity that kept industrialized societies from falling into disarray. In doing so, he was careful not to assume that the division of labor was created, deliberately or not, as a means to generate organic solidarity.[^4]

[^4]: “We use the word ‘function’ in preference to ‘end’ or ‘goal’ precisely because social phenomena generally do not exist for the usefulness of the results they produce” [@durkheim_rules_1982, 81].

Unfortunately, Durkheim was also responsible for a long-lasting association between functionalism and *organicism* [@levine_organism_1995]. This is the idea that we can think of society as an autonomous living organism whose component parts perform unique tasks that contribute to the survival and reproduction of the organism as a whole. In doing so these component parts indirectly contribute to their own survival, hence the notion that biological functions are *self*-maintaining or *self*-reproducing. According to this Durkheimian view, sociologists would become social physiologists tasked with overseeing the “normal” functioning of society and guarding against lurking social pathologies. “In many ways functionalism emerged as the science of the ‘body social,’ for it was felt that if insight into the parts of the human body could be achieved by determining how they affected bodily states, the same would be possible for society” [@turner_functionalism_1979, xii].

This organism metaphor was famously rejected by many early sociologists, among them Max Weber [-@weber_economy_1978, 15], whose interpretive style of methodological individualism was fundamentally opposed to discussions of “illegitimately reified” collective entities. Weber’s rejection of organicism is one reason why he is not usually considered a “functionalist.” And yet there is a sense in which some of Weber’s arguments can be understood as providing functionalist *why-is-it-there* explanations. For example, according to Weber, bureaucracy developed as an adaptive response to certain tasks related to the difficulties of managing large-scale armies, and also to meet the demands for public goods such as roads, water-ways, railroads, and the telegraph. “The decisive reason for the advance of bureaucratic organization has always been its purely technical superiority over any other form of organization” [@weber_economy_1978, 973]. In other words, bureaucratic forms of government proliferated because they were an efficient adaptation that outcompeted the available alternatives in its time.

Weber’s [-@weber_economy_1978, 956-80] analysis of bureaucratic organizations is also *inward-looking*. He is careful to discuss the “nuts and bolts” that constitute an efficient bureaucracy, such as formal employment, hierarchy, specialized training, long-term upwardly mobile careers, meritocratic recruitment, and the handling of everyday operations according to calculable rules applied without regard for persons. This is meant to be a *how-does-it-work* explanation. In other words, not only did he argue that bureaucratic organizations proliferated because they were adaptive, he also felt compelled to look inside bureaucracies and explain their “technical superiority” in terms of the functional arrangement of their component parts. In our view, a revisionist history of sociology would elevate Max Weber to the status of most influential functionalist thinker and not Émile Durkheim.

# Summary Overview

@fig-typology presents our proposal for a typology of functionalist arguments in the social sciences. It is a tree that branches out from two major explanatory goals. On the *why-is-it-there* side, as we discussed previously, ascribing a proper function to $X$ is a shorthand way of describing it as having a *history of selection* that explains why $X$ is there. Researchers are required to supply a concrete process that will demystify the problem of backwards causation.[^5] Broadly speaking, these selection processes come in two varieties. Those that account for the differential reproduction or copying of $X$*’*s kind *(selection)* and those that account for the differential retention of $X$ over time *(reinforcement).* An example of the latter is behavioral learning from feedback. One open question for researchers embarking on this endeavor is the extent to which some degree of deliberation (or foresight) is involved. Some philosophers argue that intentional design constitutes a separate process of purposeful selection [@griffiths_functional_1993, 419; @dennett_why_1975]. Clearly, the intentions of designers and decision-makers are key elements in many histories of selection. But we will argue that they are neither necessary nor sufficient to ground proper functions.

[^5]: That cats have claws in order to hunt prey would be a profoundly mysterious thing to say if we did not have some understanding of “natural selection.”

The second type of *why-is-it-there* explanation is different because it sacrifices historical accuracy in exchange for causal transparency. We call these “Isolated Causal Mechanisms.” The goal is to explain why some abstract form of $X$ *would* have emerged under varying historical circumstances, given that some underlying process of selection is at play. These arguments are not meant to explain why some *concrete* historical form of $X$ is there. Some examples of this form of argument include the origins of *conventions* as spontaneous solutions to coordination problems [@lewis_convention_1969], the origins of *norms* in response to common-pool resource situations [@ostrom_governing_1990], the origins of *status hierarchies* as organizational solutions to problems of cooperative goal attainment [@ridgeway_status_2019], and many more. These arguments, when successful, supply the necessary counterfactual information that allows us to reason through otherwise vexing issues such as contingency, functional equivalency, and path-dependence.

![*Branching diagram depicting the distinction between role functions and proper functions, and their associated forms of argument. A third branch depicting self-maintenance functions and an organicist framework has been omitted since, as we argue in the paper, it is not particularly relevant for sociological theory.*](images/typology.png){#fig-typology fig-align="center" width="100%"}

The second main branch of our typological tree describes two kinds of *how-does-it-work* explanations. The first provides functional and mechanistic descriptions of various phenomena that can be analyzed in terms of their component parts. “The goal is to find a set of entities and activities, to describe how they are organized together, and to show that when they are organized together just so, they produce the phenomenon one is trying to explain” [@craver_search_2013, 65]. Within this kind of argument, scientists define the role function of $X$ as its causal contribution to a complex capacity ( $\psi$ ) of some *chosen* containing system ( $S$ ). For example, the circulatory system ( $S$ ) delivers oxygen and nutrients to cells ( $\psi$ ), a capacity that we then seek to explain in terms of the organized activities of its component parts: the heart pumping, the kidney filtering, the venous valves regulating the blood’s direction of flow, and so on. None of these role functions are inherent to the isolated component parts, they are only made possible because of their interrelationship. They are also a matter of perspective, since we could easily ascribe a diagnostic function to the heart’s thumping noise if our target of inquiry was some medical monitoring system [@craver_functions_2013]. However, in neither of these two examples would we say that the role function of the heart is to contract, even though that is a perfectly valid isolated description of what the heart does.

The last type of argument in our typology focuses on one particular kind of phenomenon that deserves special attention: *goal-directed* *behavior*. People and other organisms have goals. They do not have proper functions, although we may want to ascribe them role functions in the context of some division of labor. A chair may be described as having functions, but it will never have goals. We say this because there is a widespread tendency to conflate these two words: “function” and “goal.” These words are often synonymous with “purpose,” but they are obviously not the same thing. As @nagel_goal-directed_1977 [264] remarks, “*seeing* is customarily said to be a function of eyes, rather than their goal; and *escape from a predator* is said to be the goal of a hare’s flight, rather than its function.” Following this intuition, goal-directedness has been characterized as exhibiting two signature behavioral markers: *plasticity* and *persistence* [@nagel_goal-directed_1977; @mcshea_upper-directed_2012]. Plasticity is the tendency for goal-directed entities to reach the same goal by alternative behavioral routes and from a wide range of starting points. Persistence is the capacity for error correction. It describes the tendency for goal-directed entities to adjust their behavior in the face of environmental constraints or to return to some behavioral trajectory following perturbations. This behaviorist understanding of goal-direction means there is no requirement for goal-directed entities to have mental representations of their “goals” or to pursue them in a self-conscious manner. All that matters is that their outward behavior exhibits persistence and plasticity.

The analysis of goal-directed processes is synonymous with the way in which many sociologists have presented functionalist arguments in the first place [@stinchcombe_constructing_1968]. This form of argument owes much to discussions about cybernetic machines and homeostatic systems in the 1950s, which defined goal-directedness as “control” over perturbations via some form of *negative feedback loop.* Negative feedback provides the basis for error correction in behaviors directed towards the attainment of some goal [@rosenblueth_behavior_1943]. Researchers in this tradition have sought to understand the “nuts and bolts” of these negative feedback mechanisms and how they respond to changes in the surrounding environment. The result is a kind of *how-does-it-work* explanation that deals with role functions in terms of their current instrumental contribution to some concrete goal.

In the previous section we introduced the concepts of proper functions (historical) and role functions (ahistorical). These two types of functional ascription are themselves tied to an analytical distinction between *why-is-it-there* and *how-does-it-work* questions. Following up on this, in this section we identify four general forms of functionalist argument which branch out from this original distinction. Importantly, our framework is not meant as a “gotcha” to sociologists refusing to acknowledge that they engage in *some* form of functionalist argument. We begin with “functionalism” as a troublesome word. It is vague in ways that encourage confusion. And yet it serves certain explanatory purposes that should not be abandoned. Our discussion is meant to provide ways of accomplishing those same purposes by using the more precise and less troublesome forms of expression in @fig-typology.

The rest of this paper is structured as follows. First, we examine more closely the relationship between functionalism and organicism. This detour is important since many sociologists still associate “functionalism” with the disreputed organicist framework developed by Talcott Parsons. There were many good reasons to reject this framework, but doing so came at the cost of a general skepticism among sociologists towards functional arguments. Unfortunately, these criticisms, while important, led us astray. In particular, we maintain that replacing organicist functionalism with ideas about *latent functions* [@merton_social_1968] and *hidden-causal-loops* [@elster_explaining_1983] was a mistake. We then provide a more detailed discussion of each of the forms of functionalist argument depicted in @fig-typology. Finally, we conclude with a brief discussion of the contemporary literature on collective rituals and some remarks about the relevance of functionalist arguments for other kinds of sociological inquiry.

# Organicism and Sociology

As mentioned earlier, the organicist framework provides a view of biological functions that supply the “necessary conditions” for the proper working of some organism with clearly defined boundaries and a built-in physiological drive towards survival [@mossio_organizational_2009]. This framework is also tied to a special kind of reciprocal causation. In contributing to the continuous survival of the “system” as a whole, the function of $X$ indirectly supports $X$’s own survival. This is the notion of *self-maintenance* or *self-reproduction*—e.g., the heart’s pumping blood circles back to replenish its own cells. It is also closely related to the concept of *homeostasis*, which describes the way in which organisms are driven towards the maintenance of their own stable conditions despite external perturbations (e.g., body temperature, blood pressure). Ultimately, what matters to the organicist notion of function is not that hearts have a role function or that their proper function is given by some protracted evolutionary process, but rather the heart reproduces itself by contributing to the integrity and continuous survival of the organism it belongs to.

This framework provides the building blocks for a compelling theory of biological autonomy [@moreno_biological_2015; @varela_principles_1979]. But it is not particularly relevant to sociology. Societies are not bounded living organisms and they do not cease to exist when you tamper with their parts. Nevertheless, the notion of goal-directed biological functions has been adopted at times by sociologists who mistakenly describe macro-abstractions like “society” or “capitalism” as having goals in the same mistaken way that a chair has goals.

This is essentially the theoretical commitment made by the sociologists who embraced the structural-functionalism framework developed by Talcott Parsons—i.e., a form of social physiology.[^6] As noted by Philip Selznick [-@selznick_foundations_1948, 29], “it is a postulate of the structural-functional approach that the basic need of all empirical systems is the maintenance of the integrity and continuity of the system itself.” Moreover, the concept of “function” within this framework is essentially that of a goal-directed biological role function. This is explicit in the following passage by @parsons_social_1977 [101-2, *emphasis added*]:

[^6]: @parsons_social_1977 recalls his relationship with organicism in two moments. First, as an undergraduate who first intended to specialize in biology at Amherst College in the 1920s. This early exposure to biological thinking made him receptive to the concept of homeostasis developed by Claude Bernard and Walter Cannon. References to this concept of homeostasis are scattered throughout various presentations of “functionalist explanations” in sociology (e.g., Merton 1968: 103; Stinchcombe 1968: 60). Second, through conversations during his early years at Harvard with the physiologist Lawrence Henderson, who later wrote a book titled *Pareto’s General Sociology: A Physiologist’s Interpretation*, “an important stimulus to the extension of this analysis of the nature of living systems to the socio-cultural level” [@parsons_social_1977, 118].

> \[A\] basic property of living systems is that in some sense they are self-regulating. The maintenance of relative stability, including stability of certain processes of change like the growth of an organism, in the face of substantially greater environmental variability, means that... there must be “mechanisms” that adjust the state of the system relative to changes in its environment. Thus, a fall in environmental temperature, \[for\] a warm-blooded organism, necessitates either some mechanism that has the effect of checking the rate of heat loss or some mechanism that has the effect of increasing the rate of heat production, or some combination of the two. *It is in this kind of setting that the relevant meaning of the concept “function” for present purposes is to be understood.*

Parsons used these ideas to develop a dense conceptual framework in which “social order” writ large—loosely modeled after the concept of homeostasis—emanates from socialized conformity to norms and values. He further argued that societies respond to “strain” through various self-correcting mechanisms of social control directed towards the reestablishment of social order. Thus, he reinterpreted all sorts of social phenomena as responses to “functional prerequisites” or contributions to the survival of entire social systems. This particular form of functionalism was condemned for being ahistorical and for its tendency to normatively focus on the preservation of the status quo [@turner_functionalism_1979, 109-18].[^7]

[^7]: We do not take part in a debate about whether Parsons was unfairly maligned by critics refusing to acknowledge the deeper nuance in his thoughts or not. However, it is only fair to point out that he was well aware of the “overtones of teleology” and the “dangers of hypostatization” that resulted from talking about the “needs” of a “system.” Furthermore, he was willing to concede at times that this was all a figure of speech—i.e., “a sort of shorthand for the description of complex processes which we do not yet fully understand” [@parsons_toward_1951, 241].

It is easy to see how the alleged conservative nature of functionalist explanations follows from an organicist framework that allows for value judgments to be grounded on the presumed authority of natural science [@levine_organism_1995]. This view has often been criticized as a sort of “Panglossian paradigm” that assumes that *all* the parts of an organism are *good for something* until proven otherwise. Since organisms tend to die when you tamper with their parts, social physiologists are wary of any deliberate change to current institutions. Thus, conservatism follows from the “naturalistic fallacy” of mistaking what is for what *ought* to be, and from the unwarranted belief that societies resemble living organisms.

However, organicism has often been deployed by radical social theorists. For example, some Marxist theories, but certainly not all, conceptualize the state as tasked with ensuring the survival of the capitalist system. The idea is that capitalist societies are inherently prone to crises and that, therefore, the state serves (and must serve) a *maintenance* *function* aimed at protecting, repairing, and reproducing the capitalist system as a whole [@barrow_critical_1993]. In this upside-down version of the “Panglossian paradigm,” it is capitalism that has the built-in goal of survival and every social institution is assumed to be in the service of this goal.

Ultimately, what resulted from the organicist framework was not the idea that societies resemble living organisms in a literal sense. This stronger claim could be easily disregarded by early functionalists as a convenient metaphor. Instead, it resulted in a general image of social systems as highly bounded and internally differentiated entities whose component parts are supportive of one another. These are social systems that exhibit what @merton_social_1968 called “functional unity” and philosopher Samir Okasha [-@okasha_agents_2018] has recently termed “unity of purpose.” However, this still provides an untenable framework to the extent in which it is applied to macro-abstractions with overarching survival goals.

\noindent \textit{The Specter of Merton-Elster}

The backlash against organicist functionalism was widespread. Many sociologists contributed to the ensuing disrepute of “functionalism” in sociology. For simplicity we focus on the contributions of two authors. First, the “internal” critique of Robert Merton, who sought to make structural-functionalism more flexible by moving it away from organicist postulates. Second, the “external” critique Jon Elster, who sought to eliminate functionalist explanations altogether. Their critiques have become so entrenched that it is reasonable to think of them now as canon. It is also through their joint influence that the notion of a valid functional explanation became synonymous with the notion of *hidden-causal-loops*, which we have deliberately excluded from our typology.

Merton’s contribution to the debate was twofold. First, he criticized the functionalist writings of his contemporaries for relying on three implausible postulates. The *functional unity postulate* holds that the component parts of a system must show high degrees of integration. But Merton contended that the degree of “integration” of a system should have always been an empirical question and never an a priori assumption. The *functional universality postulate* holds that all component parts fulfill some need or perform some “vital” function for the system as a whole (a “Panglossian” assumption). In dropping these two postulates, Merton believed structural-functionalism could make sense of group conflict and dysfunction.

> “Far more useful as a directive for research would seem the provisional assumption that persisting cultural forms have a *net balance of functional consequences* either for the society considered as a unit or for subgroups sufficiently powerful to retain these forms intact, by means of direct coercion or indirect persuasion. This formulation at once avoids the tendency of functional analysis to concentrate on positive functions and directs the attention of the research worker to other types of consequences as well” [@merton_social_1968, 86].

Finally, the *indispensability postulate* holds that the parts of a system are irreplaceable, to which Merton noted that the same “functional requisites,” if such things exist, can be met by a host of alternative structures. In general it is a mistake to infer causes from their effects [@hempel_aspects_1965, 310]. This logical fallacy is known as “affirming the consequent.” Thus, Merton acknowledged that the organicist concept of “function” does not provide answers to *why-is-it-there* questions and that the same goal (e.g., food-gathering) may be achieved through various “functionally equivalent” means.

Note that it is hard to imagine how any of these postulates would ever be implicit in any form of argument that responds to *why-is-it-there* or *how-does-it-work* questions. There is no reason to believe that proper functions or role functions indicate any commitment to some form of “Panglossian paradigm” or that function bearers (e.g., institutions) are irreplaceable components of some system as a whole. However, it is relatively straightforward to see how all of these postulates follow comfortably if one takes an organicist stance on functionalist explanation.

Merton’s second contribution was the introduction of the now common distinction between “manifest” and “latent” functions. Manifest functions are those consequences of behavior that are intended and recognized by the participants in some system, whereas latent functions are always unintended *and* unrecognized [@merton_social_1968, 105]. The intuition behind this distinction is relatively straightforward. People often struggle to articulate the reasons for why they behave in certain ways and their resulting accounts tend to be fairly inconsistent. In many cases their behavior is more likely to be governed by impulse, habits, or desires which remain in a state of inarticulate automaticity or unawareness [@small_using_2021; @vaisey_motivation_2009]. As such, the manifest-latent distinction gives sociologists a license to go behind people’s back and discover the “true” causes of behavior hidden beneath the surface of appearances. Furthermore, it provides sociologists with the opportunity to make sense of seemingly “irrational” behaviors. For example, Merton notes that, according to the anthropological record, the “manifest” function of Hopi ceremonials is to produce rainfall. On the assumption that this is physically impossible, that no such ritual has ever accomplished this task, we cannot explain its persistence by appealing to its nominal purpose. Instead, the anthropologist appeals to the “latent” function of reinforcing kinship ties, which in turn contributes to the continuous survival of the group as a whole.

Elster’s contribution was also twofold and builds directly on the Mertonian ideas we have just described. First, he distinguished between “strong” and “weak” versions of functionalism. The strong programme is essentially the same organicist “Panglossian paradigm” criticized in Merton’s discussion of the three implausible postulates. In contrast, the weak programme is depicted as holding that “whenever social phenomena have consequences that are beneficial, unintended and unrecognized, they can also be explained by these consequences” [@elster_explaining_1983, 57]. This distinction has become commonplace in sociology. As noted by Charles Tilly [-@tilly_relational_2000, 784]:

> Strong functional arguments say that social arrangements exist because they serve overarching systems. Weak functional arguments say that social arrangements exist because they simultaneously serve particular actors and produce effects that in turn reproduce the social arrangements.

Second, @elster_explaining_1983 [57] maintained that only the “weak” version was capable of providing any plausible explanation and offered a schematic of how such an explanation should look like:

> An institution or a behavioral pattern $X$ is explained by its function $F$ for group $Z$ if and only if:
>
> 1.  $F$ is an effect of $X$;
> 2.  $F$ is beneficial for $Z$;
> 3.  $F$ is unintended by the actors producing $X$;
> 4.  $F$ (or at least the causal relation between $X$ and $F$) is unrecognized by the actors in $Z$;
> 5.  $F$ maintains $X$ by a causal feedback loop passing through $Z$.

This template for how functional arguments ought to look proved to be very influential. There are plenty of reasons to like this framework. The addition of concrete groups ( $Z$ ) means that there is no room in functionalist explanations for ill-defined organic totalities. It also leaves open the possibility for considering conflict, contradiction, and domination among groups. This feature is conspicuously absent from “Panglossian” versions of organicism. More importantly, Elster noted that the main reason functional explanations fail is because the actual causal process through which $F$ explains $X$ (condition 5) is postulated rather than demonstrated. This is the so-called “missing mechanism” critique of functionalist arguments [@van_riel_search_2020].

However, the insistence that valid functional explanation should deal exclusively with latent functions was an enormous mistake (conditions 3 and 4). There are very few explanations that can actually meet these criteria. This is because the distinction between manifest and latent functions does not withstand closer scrutiny. @merton_social_1968 uses the term “latent” to refer to a wide variety of phenomena, some of which are either unintended, unrecognized, unanticipated, or undisclosed. But all of these terms have distinct meanings. Furthermore, it is extremely rare for some recurrent phenomenon to be so cognitively opaque that its consequences are both unintended and unrecognized by every single person. @elster_explaining_1983 [58] even rejects behavioral learning from feedback as an example of a successful functional explanation because it requires that individuals at least recognize the causal link between behaviors and rewards (against condition 4).[^8] In contrast, as we argue in the next section, behavioral learning from feedback provides a valid selection mechanism that explains the *differential retention* of some behaviors at the expense of others [@dennett_why_1975]. It gives rise to proper functions.

[^8]: Elster argued that dropping the requirement that functions are unintended and unrecognized puts us in the realm of *intentional* explanations, which are somehow better served by some sort of *rational-choice* argument. The implication is that rational choice and functionalism are somehow at odds with each other.

The requirement that individuals do not know what they are doing is not a core feature of any kind of functionalist argument. It is hard to think of any reason as to why this should be the case. Even Merton’s famous analysis of the “political machine” involves individuals who are quite aware of the consequences of their own behavior. More importantly, the insistence that some “benefit” (whatever it may be) is also unrecognized and unintended provides hidden-loop conjectures with an extra layer of protection against empirical refutation. Relatedly, it is very easy to speculate that these beneficiaries may be following a hidden agenda or that they are being directed towards a “goal” that they rather keep secret (or that is secret to themselves). This ultimately led a generation of sociologists to conclude that all functionalist explanations were suspect. In other words, the hidden-causal-loop framework throws the baby out with the bathwater.

This leads to the current state of affairs. A leading French sociologist once remarked that “the word functionalism is one of those concepts that is used as an insult, and so is not much use scientifically. I simply say—this is something sociologists can agree on—that an institution that is constantly used over a long period merits the hypothesis that it has some function, it does something” [@bourdieu_state_2018, 26]. He is not alone. It is still relatively common for sociologists to describe various social phenomena as having a function or serving a purpose. For example, Charles Tilly [-@tilly_relational_2000, 784] describes his arguments about categorical inequality as being “weakly functional” in the sense that we should expect powerful groups of individuals to be more effective at creating social structures that protect their interests and reproduce their dominant position. Similarly, Eduardo Bonilla-Silva [-@bonilla-silva_racism_2021, 9-10] argues that “the secret of racial structures and racial inequality the world over” is that “they exist because they benefit members of the dominant race.” Clearly, there is a sense in which functional ascription is meant to add some kind of explanatory depth that is hard to obtain elsewhere.

In this section, we have argued that the most important criticisms of functionalist arguments were directed towards organicism, which carries a particular conception of *self*-maintenance role functions. The critics were right in rejecting organicist functionalism. But they were wrong in replacing it with the notion of hidden-causal-loops, which directed our attention away from the more tenable ways of making functionalist arguments we discuss in what remains of this paper.

# History of Selection

Anything that exists in this world has a *causal history*. It is the endpoint of a vast branching structure of events pointing back in time [@lewis_causal_1986: 242]. This is true of beliefs, behaviors, rituals, artifacts, organizations, rules, and many other social phenomena. If we further describe $X$ as having a proper function, we mean to say that there is a selection process that captures a large chunk of this causal history. We are then tasked with providing a convincing history of selection. Hence the notion of proper functions as “selected effects” [@neander_functions_1991].

The concept of proper function was first developed as a basic form of argument “which looks to the *history* of an item to determine its function rather than to the item’s present properties or dispositions” [@millikan_defense_1989, 288]. This history will look differently depending on the type of phenomena we choose to explain, but some selection process will always be involved. The alternative to selection corresponds to what biologists call “random drift” or “neutral” evolution. Jack Goldstone [@goldstone_initial_1998, 833] refers to these alternative historical accounts as Dr. Seuss-style explanations in which “it just happened that this happened first, then this, then that, and is not likely to happen that way again.” These alternatives often capture important slices (or the entirety) of many causal histories. But they do not give rise to proper functions.

All processes of selection can be distinguished by whether they account for (1) the *differential reproduction* or *copying* of $X$*’*s kind or (2) the *differential retention* of $X$ over time. The choice of one or the other boils down to whether we can conceive of $X$ (a trait, a belief, a behavior) as something that is sustained in time via reproduction or not. For example, it is hard to conceive of behavioral learning from feedback as involving anything like reproduction. A pattern of behavior may have pleasant consequences for other people, who in turn reward the behavior in the form of status, reciprocity, or access to valued resources [@stinchcombe_constructing_1968, 86]. Such a situation is best described in terms of the differential retention of one behavioral disposition over another [@garson_generalized_2017, 530]. As such, these behavioral dispositions will have proper functions because they are the outcome of a reinforcement process that explains their differential retention over time.

Natural selection of traits in a population provides the classic example of a selection process that explains differential reproduction over time. Consider the fact that many animals in the Arctic have white fur. The typical evolutionary explanation would posit that white fur has a particular “effect.” It allows creatures to escape detection more easily in this environment. This trait then has a proper function because it increases the average fitness of the population of Arctic creatures with white fur.[^9] These kinds of proper functions are often described as “adaptations,” but sometimes $X$ is best described as a “kludge”—i.e., selected not for its optimality or superiority, but rather because it was “good enough” [@simon_rational_1956]. It is important to note that other animals may be subjected to different processes of selection. Not every evolved trait can be described in terms of survival enhancing adaptations. For example, the process of “sexual selection” is meant to explain the extravagant long tails of male peacocks by reference to the mating preferences of female birds. Similarly, consider the fact that the size and shape of many animal characteristics has been bred into them for human purposes. The smooshed-up faces of bulldogs have no survival enhancing properties. They are *for* pleasing people [@perlman_changing_2009, 23]. That is their proper function.

[^9]: This example is taken from @simon_sciences_1996 [7].

Relatedly, sociologists have long argued that the differential reproduction and retention of various organizational forms is contingent on *perceived* fitness. Organizations may not adopt new technologies or procedures because of their *technical efficiency*, but rather because of their *cultural legitimacy* [@jepperson_institutional_2021; @dimaggio_iron_1983]. In other cases the adoption of organizational forms may be the result of military conquest and other kinds of *coercive processes*—i.e., they satisfy the interests and preferences of powerholders. “Organizations compete not just for resources and customers, but for political power and institutional legitimacy, for social as well as economic fitness” [@dimaggio_iron_1983, 150].

A history of selection will sometimes attempt to explain $X$ by appealing to the foresight and purposes of the human beings responsible for creating $X$ in the first place. Intentional design has long been described as a form of “virtual” selection that takes place inside the mind of the designer [@griffiths_functional_1993, 419]. For example, there is a very clear sense in which the existence of some *artifacts* is due to their intended functions, which are typically contained in their names: vegetable peeler, screwdriver, typewriter, bookmark, clothes hanger, etc. The proper function of artifacts in these cases is taken to be transparently obvious since it can be found in the intentions of designers and their purposeful history of selection. However, intentional design is not sufficient to ground proper functions [@preston_why_1998; @perlman_changing_2009]. A designer’s intentions are just one part of the larger causal history that gives shape to whatever $X$ (artifact, rule, institution) we are interested in explaining. Proper functions arise from a history of which will not always coincide with original intent. This becomes much more clearer once we deal with two special kinds of function: (1) unintended proper functions and (2) phantom functions.

An *unintended proper function* is the kind we would attribute to unintended consequences. The history of technology is riddled with such cases of accidental discovery. So is the history of consumer products. For example, social media companies have often found themselves surprised by user innovations that push the character and purpose of their products in unforeseen directions [@fourcade_ordinal_2024, 60-1]. We can also see unintended proper functions in the realm of “social control.” For example, @sauder_discipline_2009 describe the establishment of law school rankings that force individuals into a dynamic that is both recognized and resented by almost everyone participating in it. These participants are then punished or rewarded on the basis of how their activities manage to “move them up” the rankings or not—e.g., hiring decisions, resources allocation, and clever gaming strategies. Thus, any stable behavioral disposition that results from this unintended feedback mechanism may have a proper function since it will have an adequate history of selection.

*Phantom functions* typically describe artifacts and rituals that cannot actually do what they are intended to do [@preston_philosophy_2012, 177]. A typical example is an amulet’s function of warding off ghosts. Assuming that this is impossible, that no such amulet has performed this function or ever will, then the historical reproduction of such a trinket cannot be attributed to its intended effects. Furthermore, many producers and users of such trinkets will be aware of this impossibility and yet still be willing to “play along” for other reasons. Merton’s [-@merton_social_1968] discussion of Hopi ceremonials and their capacity to produce abundant rainfall provides a further example. In other words, phantom functions correspond to what an older generation of sociologists would disregard entirely as mere “manifest” functions. But the difference in vocabulary is important since all phantom functions are manifest functions but not all manifest functions are phantom functions. Furthermore, phantom functions may still have “proper functions,” for example, when they have been selected for their cultural legitimacy rather than for their means-ends technical efficiency.

Studies of technology provide a further example that complicates the relationship between intentions and the proper functions of artifacts. The “problems” for which artifacts can be said to be successful solutions also have a history of their own. @pinch_social_1984 describe two kinds of mechanisms through which some artifacts become successful and out reproduce competing artifacts over time. First, various relevant social groups may come to perceive the artifact as a solution to a problem because of the *rhetorical efforts* made by producers (e.g., advertising). Second, success may be achieved via the *redefinition of a problem.* This means that the artifact is presented as the solution to a new and previously unacknowledged problem. In this case, the artifact may exist well before the installment of the selection process that ensures its reproduction over time. It is for these reasons that our understanding of proper functions must accommodate the fact that any history of selection that takes “problems” and “goals” to be devoid of a history of their own risks failing on empirical grounds.

Finally, every history of selection assumes a source of variation in the background, for there can be no selection in the absence of variation and difference. To put it another way, selection alone can never fully answer a *why-is-it-there* question. It may be able to explain the differential reproduction or retention of $X$ over time, but it cannot explain the origin of $X$. Some mechanisms that produce variation may be characterized as *blind*, as in the random genetic mutation underlying natural selection. Other mechanisms are *intentional*, as in goal-directed trial-and-error or what some anthropologists call “guided variation” [@richerson_not_2008, 69].

In the words of @aldrich_organizations_2020 [19]:

> Intentional variations occur when people or organizations actively attempt to generate alternatives and seek solutions to problems. They result from conscious responses to problematic situations, planning sessions, advice from outside consultants, and so forth. Blind variations, by contrast, occur independently of conscious planning. They result not from intentional responses to adaptation pressures but rather from accidents, chance, luck, conflict, malfeasance, and so forth.

This is why we maintain that intentional design is best conceived as a source of variation. It may be construed as a special kind of problem solving that gives rise to new role functions, but it is not in itself the kind of historical selection process that gives rise to proper functions.

Past episodes of selection are also best conceived as sources of variation on which current episodes of selection can now operate. In other words, the selection processes of the past contribute to the stock of present day variation. This is how we typically conceive vestigial functions. If a selection process disappears, then the proper function also disappears, it becomes vestigial. Much like the human appendix, it exists now by sheer inertia or force of habit.[^10] Relatedly, new processes of selection create new functions from old ones. For example, some biologists maintain that insects first developed small winglets that were originally adapted for thermoregulation and not for flight [@kingsolver_aerodynamics_1985]. It was only after these wings reached a certain shape and size that they could be repurposed for flying, at which point a new process of selection kicked in. Similarly, sociologists have documented how the Young Men’s Christian Association (YMCA) slowly responded to changing selection pressures by expanding its membership to include individuals from all ages and religions. This shifted its goals from a narrow focus on religious proselytism to a broader focus on “character development” via the provision of physical, intellectual, and social activities [@zald_evangelism_1963].

[^10]: Durkheim [-@durkheim_rules_1982, 79] was able to recognize this early on: “a \[social\] fact can exist without serving any purpose, either because it has never been used to further any vital goal or because, having once been of use, it has lost all utility but continues to exist merely through force of custom. There are even more instances of such survivals in society than in the human organism.”

In other words, every proper function starts out as a “role function” encountering a new process of selection. But role functions are also historical entities in their own right. They do not spontaneously pop into existence. They may be the outcome of past processes of selection or they may be the endpoint of random historical trajectories. Most often, if we look far enough into the past, they are a combination of both. Thus, if we decide to incorporate too much detail, a history of selection may spin out of control and turn into an enterprise that resembles geology more than it does genealogy.

As @lewis_causal_1986 [214] remarks,

> Any particular event that we might wish to explain stands at the end of a long and complicated causal history. We might imagine a world where causal histories are short and simple; but in the world as we know it, the only question is whether they are infinite or merely enormous.

# Isolated Causal Mechanisms

Sometimes we are not interested in providing detailed explanations of particular phenomena lying at the endpoint of some long and complicated causal history. Instead, we might be more interested in isolating a causal mechanism that can, in principle, generalize to a broader class of phenomena. Lewis’ [-@lewis_convention_1969] discussion of the origins of conventions provides a good example. Using a very simple mathematical model, he contends that conventions spontaneously emerge as solutions to coordination problems (e.g., driving on the right side of the road). This is why we can ascribe proper functions to them. But conventions, by definition, are also arbitrary and path-dependent in the sense that history could have gone any number of ways (e.g., driving on the left side of the road). In other words, when faced with a coordination problem, human groups will spontaneously develop some convention, but we cannot know which in advance. Once such a solution becomes locked-in-place it is difficult to change.[^11]

[^11]: @oconnor_origins_2019 [26, 89] shows that arbitrariness can be construed as a matter of degree and that coordination problems can be thought of as existing along a spectrum going from complete "conventionality” (where there are many equally good solutions) to complete "functionality” (where only one solution is deemed optimal).

These isolated causal mechanisms are meant to answer why-is-it-there questions in a special way. The origins-of-conventions argument posits that $X$ exists because it provides a solution to some ongoing coordination problem ( $F$ ). Except that $X$ is now a *generalized target*—“a generalized phenomenon is chosen as a target, not a specific instance of that phenomenon” [@weisberg_simulation_2012, 114]. Thus, we could criticize the argument by noting that it is empirically wrong in a very literal sense. It looks like an historical account but it actually skips over historical research and offers instead a speculative story about what *may* have happened [@granovetter_society_2017, 6]. But this is not the purpose of such an account. The goal is not merely to provide a conjecture, but to explore a causal mechanism using a model [@weisberg_simulation_2012, 120].

The literature on cultural evolution provides further instances of this strategy. This literature argues that some rules of imitation (or “social learning heuristics”) have proper functions in the sense that they have been “selected for” via natural selection [@richerson_not_2008]. These copying rules​​ are said to be responsible for differential reproduction of various kinds of ideas, beliefs, values, skills, attitudes, and behaviors. “There is a great deal of adaptive information embodied in both who holds ideas and how common the ideas are” [@henrich_evolution_2003, 120].[^12] Crucially, it is not the *content* of these learned behaviors that is necessarily adaptive; it is the imitation rule itself that is adaptive insofar as it increases the average fitness of the population by reducing the costs of acquiring useful information. As a result, some concrete behaviors and ideas may turn out to have “neutral” or even “harmful” effects. These “maladaptations” may spread if they happen to be statistically correlated with high-status individuals or military successful groups:

[^12]: The literature on cultural evolution has developed a complex taxonomy of such copying rules—e.g., prestige-bias, success-bias, homophily-bias, and conformity-bias [@henrich_evolution_2003; @richerson_not_2008]. This taxonomy partially overlaps with what neoinstitutionalists call coercive, normative, and mimetic isomorphism [@dimaggio_iron_1983].

> “…it is often very unclear which of an individual’s many traits have led to success. Are people successful because of how they tend their farms, cook their food, or make sacrifices to the spirits, or all three? Because of this ambiguity, humans may have evolved the propensity to copy successful individuals across a wide range of cultural traits, only some of which may actually relate to the individuals’ success. If information is costly, it turns out that this strategy will be favored by natural selection even though it may allow neutral and maladaptive traits to hitchhike along with adaptive cultural traits” [@henrich_evolution_2003, 130].

Much of the literature on institutional isomorphism follows a similar path. The notion of mimetic isomorphism can be construed in terms of what cultural evolutionists call conformity-bias or success-bias. These rules of imitation seem especially well suited to deal with information-poor environments—i.e., “copy when uncertain.” This is how @dimaggio_iron_1983 attempt to explain the spread of various organizational structures that could hardly be described as adaptive in the narrow sense of means-ends technical efficiency. @strang_search_2001 provide an isolated causal mechanism (an agent-based model) that shows how organizations engaging in success-imitation are especially susceptible to adopt worthless managerial fads.

These models sacrifice historical accuracy in exchange for causal transparency. This is what distinguishes them from speculative “just-so stories” that lack both [@gould_spandrels_1979]. The explanatory target is not some concrete feature of the world standing at the endpoint of a long and complicated causal history, but rather a selection mechanism that can potentially capture a cross section of many causal histories. These models tend to lack direct empirical support. They borrow strength from their compatibility with the available concepts and stylized facts scattered throughout various subfields. Their plausibility increases as they are prodded for inconsistencies, compared to alternative models, and revised accordingly. More importantly, they are capable of providing important counterfactual information that cannot be obtained by more detailed histories of selection.

# Functional Analysis and Mechanistic Explanation

As we have seen, functional explanations premised on the idea that “$X$ is there because it does $F$” must direct their attention to some historical process of selection or reinforcement. Knowledge about causal histories, however, is often hard to come by (and in many cases impossible). Depending on our research interests, this may not be a problem. History is altogether unnecessary for the attribution of role functions and the answering of *how-does-it-work* questions. These questions demand a different kind of explanation altogether.

The form of argument we consider in this section provides a sort of “mechanistic” description that looks “inside” some phenomenon with the aim of revealing the “nuts and bolts” responsible for its behavior [@craver_functions_2013]. Here, the role function of $X$ is its contribution to some feature or complex capacity ( $\psi$ ) of a “containing system” that has been *chosen* by researchers for being especially worthy of attention (e.g., a government’s capacity to surveil, an army’s capacity to destroy). These higher-level phenomena are then explained in terms of the organized activities of their component parts or their “functional arrangement.” For example, fingerprints contribute to the overall surveillance capacity ( $\psi$ ) of law-enforcement organizations insofar as these organizations also have an infrastructure that collects, stores, and retrieves them—i.e., their contribution cannot be understood without reference to the role functions of other interacting parts. Importantly, *this* function of fingerprints in *this* system does not have a history of selection. Fingerprints themselves do not exist for the sake of surveillance systems. The capacity of fingerprints to contribute to larger surveillance systems may be better characterized as an *exaptation* [@gould_exaptation-missing_1982]. A trait designed for some other purpose (or no purpose at all) is often co-opted to serve new purposes. When trying to understand these exaptive purposes, focusing on the historical evolution of fingerprints and other component parts of a surveillance system will not help us achieve our explanatory goal.

This kind of argument is prominent in the study of organizations, which are transparent examples of “containing systems.” Organizations carry out specific work—such as processing raw materials, data, or individuals—that results in the completion of some *task* or the delivery of some *end product.* We can explain *how* this work gets done by decomposing it into a set of interdependent role functions distributed across a wide range of individuals and technological artifacts. An example of this is found in explanations of *dead reckoning* ( $\psi$ ) in organizations, which is the capacity to predict the position of moving objects in space without relying on direct observation. For example, @hutchins_cognition_1995 describes how navigation crews manage to find their way across the ocean in terms of a cognitive “functional system” composed of various people interacting with tools and in coordination with each other. More recently, @vaughan_dead_2021 has sought to explain how air traffic control systems manage to guarantee flight safety, which involves monitoring the positions and flight paths of thousands of planes while at the same time avoiding mid-air or runway collisions.

There are two conditions under which such an argument might fail or succeed. Functional and mechanistic descriptions fail when (1) we mischaracterize the phenomena under investigation or (2) we provide an inadequate decomposition. The first might happen when one tries to explain a fictitious phenomenon, as when there is no plausible “containing system” to begin with. It may also happen when $\psi$ is incorrectly specified or corresponds to what we described earlier as a “phantom function”—e.g., the rainfall producing capacity of a Hopi ceremonial.[^13] Mischaracterization may also occur via “lumping together two separable phenomena produced by different mechanisms” or “incorrectly splitting one phenomenon into many” [@craver_search_2013, 60].

[^13]: “In the abstract, it need hardly be said that before one proceeds to explain or to interpret a phenomenon, it is advisable to establish that the phenomenon actually exists, that it is enough of a regularity to require and to allow explanation. Yet, sometimes in science as often in everyday life, explanations are provided of matters that are not and never were” [@merton_three_1987, 2].

The second requirement for a successful functional description is that it provides an adequate decomposition. Following @bechtel_explanation_2005, we can distinguish between two forms of decomposition: First, a structural decomposition in which component parts are described in terms of their physical substrate ( $X_1$, $X_2$, ..., $Xn$ ). Second, a functional decomposition in which component parts are described in terms of their relevant activities ( $F_1$, $F_2$, ..., $F_n$ ). The latter operates “at a level of abstraction that identifies constituent processes or parts in terms of what they do or contribute, rather than in terms of their intrinsic constitutions: their functions rather than their forms. Anything across which there is a drop in electrical potential is a resistor. Anything across which there is a pressure gain is a pump” [@cummins_traits_2009, 74]. In other words, the same high-level capacity can be instantiated in several different ways, a single functional decomposition can be compatible with various physical structures.[^14]

[^14]: Philosophers call this “multiple realizability.”

Importantly, these explanations become more plausible when both kinds of decomposition are linked with each other in a process known as *localization* [@bechtel_discovering_1993; @lizardo_analytical_2023]. The ability to link role functions with their corresponding real-world entities serves to corroborate each decomposition. Failure to do so can be grounds for doubting the existence of either, as with most conspiracy theories and other speculative “just-so” stories.

This does not imply that we should always expect a one-to-one correspondence between each structural component and their corresponding role function. @bechtel_discovering_1993 refer to this as a “simple” or “direct” localization. Instead, it may be the case that a single component is involved in multiple tasks, for example, when individuals in an organization take on multiple roles under varying circumstances. It may also be the case that some role functions are themselves the product of several independent components acting simultaneously.

Nonetheless, it remains true that learning about the properties of component parts helps us reason about the types of activities they might engage in and the role functions that can be credibly attributed to them. For example, the subfield of “culture and cognition” has promised to provide constraints on the sorts of activities individuals can engage within the context of “cultural phenomena” [@dimaggio_culture_1997; @martin_lifes_2010; @lizardo_improving_2017]. An emphasis on decomposition and localization stands as an important corrective to alternative views that prefer to see “culture” as delocalized and immaterial, an “ontologically unmoored macro-abstraction” [@lizardo_analytical_2023, 286]. The same can be said of other kinds of social phenomena. We cannot simply postulate the existence of some abstract social “system” without actually going through the trouble of answering the *how-does-it-work* question.

Finally, claiming that all social phenomena are ultimately located in human bodies and material artifacts does not signal a commitment to individualism and other forms of micro reductionism. Even adherents of macro-causality will happily concede that complex social structures are ultimately instantiated in people—an “ontological truism” [@jepperson_institutional_2021, 142]. However, while it is one thing to maintain that the building blocks of social systems are individual people and material artifacts, it is quite another to figure out how their organized activities contribute to some larger phenomena.

# Goal-Directed Processes

The form of argument we consider in this section helps us explain how some goal-directed system achieves some “goal.” Unlike the organicist perspective, this form of argument is not reduced to an exclusive concern with the survival or reproductive goals of some organism. Nor does it require role functions to be *self*-maintaining. It only requires that role functions are instrumental contributions to the attainment of some goal. For example, it would not seek to explain an army’s capacity to destroy, but rather the way in which army generals accomplish the goal of invading some territory. Most notably, what distinguishes the analysis of goal-directed processes from other forms of argument is that the thing-to-be-explained is a special kind of *behavior* marked by persistence and plasticity [@nagel_goal-directed_1977, 265; @mcshea_upper-directed_2012, 664].

As we discussed previously, *plasticity* is the tendency for goal-directed entities to find a particular behavioral path towards some goal from a wide range of starting points. In turn, *persistence* is the capacity for error correction. It describes the tendency for goal-directed entities to change their behavior in the face of environmental constraints, such that if one path towards a goal is blocked, an alternative path is then taken. Thus, examples of goal-directed entities include human beings, but extend to simpler organisms like migrating birds, bacteria, and even to some technological artifacts like homing torpedoes and heat-seeking missiles. Importantly, only a subset of these entities can be said to have intentions or pursue goals of their own: individuals and other living organisms.

The paradigmatic example of goal-direction is closer to rational-choice theory than it is to the macro-functionalist systems theorizing of Talcott Parsons: individuals intentionally pursuing their “wants.” For example, some people want to buy cars, some generals want to win wars. In each case, the individuals involved will assess the future consequences of their own behavior in terms of how close it will bring them to their goals. This example presumes individuals tinkering around with different kinds of behavior, or the usage of different tools, until they achieve results that are deemed “good enough” for the purpose at hand [@simon_rational_1956]. Furthermore, since we expect individuals to find many ways of achieving the same goal (or plasticity), we can see how the so-called problem of “functional equivalents” is irrelevant to this form of argument [@stinchcombe_constructing_1968, 80].

The most influential approach in the 20th century for making sense of goal-directedness was the short-lived science of cybernetics. It began with the exploration of feedback mechanisms during the Second World War, as systems engineers in the USA tried to design anti-aircraft guns that would predict the location of German planes and adjust accordingly [@galison_ontology_1994]. After the war, this exploration morphed into a loose interdisciplinary effort at shedding light on all sorts of technological, biological, and social systems. A series of conferences, known as the Macy Conferences, were held in New York City from 1946 to 1953 and brought together engineers, physicians, anthropologists, psychologists, and sociologists [@kline_cybernetics_2015]. It served as a sort of interdisciplinary hub that coalesced around a set of shared metaphors. The first conference, held in New York City, was aptly titled “Feedback Mechanisms and Circular Causal Systems in Biological and Social Systems.”

Crucially, this forms the intellectual landscape behind Arthur Stinchcombe’s influential definition of functional explanations in sociology: “By a functional explanation we mean one in which the *consequences* of some behavior or social arrangement are essential elements of the *causes* of that behavior” [@stinchcombe_constructing_1968, 80]. This view of circular causality incorporates the cybernetic idea of a *negative feedback loop* which provides the basis for error correction in behaviors directed to the attainment of some goal. The cyberneticists claimed that negative feedback alone was responsible for producing all forms of all goal-directed or teleological behavior [@rosenblueth_behavior_1943, 19].

Insofar as cyberneticist accounts were used to understand how an organism accomplished its survival goal, it really was just the continuation of an organicist framework under a different and more fashionable name. In fact, the core ideas about negative feedback were loosely modeled after the concept of homeostasis. Parsons himself shifted towards a cybernetic depiction of social systems in his later writings. This is why some ideal-typical descriptions of “functioning systems” in sociology resemble the inner workings of a central heating system, with a thermostat capable of detecting changes in room temperature and using that information to adjust the furnace accordingly [@barnes_elements_1995, 38]. This negative feedback loop requires at least three components with their corresponding role functions: (1) a built-in *goal*; (2) a *monitor* capable of detecting a “signal” from the environment and comparing it with such goal; and (3) an *effector* in charge of eliciting an appropriate behavioral response so that the signal is adjusted accordingly. These components, *together with the enclosing environment,* form a goal-directed process. Importantly, much of what we previously said about good functional and mechanistic explanations carries into the analysis of goal-directed processes (e.g., the importance of decomposition and localization).

Ideas about cybernetic negative feedback loops are a central component in many theories across various disciplines [e.g., @tomasello_evolution_2022; @berridge_motivation_2004]. They also figure prominently in sociological theories about identity and social interaction, such as identity control theory [@burke_identity_2022], affect control theory [@smith-lovin_analyzing_1988], and balance theory [@cartwright_structural_1956; @rawlings2017]. All of them attempt to explain a slice of social behavior by making reference to some kind of “homeostatic variable” or built-in goal—i.e., identity standard, deflection, and balance. According to these theories, human behavior resembles that of an elaborate thermostat, monitoring social situations and eliciting appropriate behaviors aimed at keeping perceptions in line with some form of cultural expectation (comparable to the stable room temperature maintained by central heating systems). More general notions in sociology such about “control” or “self-correcting behavior” derive from ideas about negative feedback loops [@robinson_control_2007].

Importantly, goal-directed entities are not required to have mental representations of their “goals” or to pursue them in a self-conscious manner. This is obvious in the thermostat system, where there is no conscious thought anywhere to be seen and the “goal” is simply the outcome of a causal structure that has been put in place. But it is less obvious in many of the activities that we take for granted. For instance, we only become aware of our desire to breathe when something stops us from doing so, at which point we will struggle to do so in ways that are marked by persistence and plasticity.

This point is not a matter of philosophical nitpicking. Functionalist arguments in sociology have a tendency to mistakenly attribute goals and goal-direction to macro-abstractions like “society” or “capitalism.” Moreover, there is often an important disconnect between subjective goals and the broader notion of goal-direction. Consider Karl Marx’s famous depiction of the “goals” of the individual capitalist as being relatively inconsequential. This is because the competitive dynamics of capitalist production confront the individual capitalist as “a coercive force external to him” [@marx_capital_1992, 381]. Thus, individual capitalists will go bankrupt unless they behave in a certain way. Two points are worth emphasizing here. First, the individual capitalist has goals and “wants,” capitalism itself does not. The latter is best understood as describing the large-scale structure of the environment in which individual capitalists are immersed. Second, the behavior of capitalists is goal-directed in ways that may or may not overlap with their individual desires or intentions. In other words, their choices are rewarded or punished in ways that mark the pursuit of profit with persistence and plasticity.

# Case Study: Collective Rituals

We illustrate the usefulness of our typology by reexamining collective rituals, a classic example in the history of functionalist explanations in the social sciences. Many canonical presentations of functionalist sociology are littered with references to anthropological depictions of ritual practices [@merton_social_1968; @stinchcombe_constructing_1968; @elster_explaining_1983].[^15] These rituals have fascinated social scientists because they seemingly produce “useful effects” through means that are causally opaque, demonstrating a sort of hidden rationality beneath the surface of “superstitious” and “seemingly irrational” phantom functions. @durkheim_elementary_1995 argued that collective rituals produce symbolic markers of group membership and generate a special kind of emotional arousal (“collective effervescence”) which in turn results in “social cohesion.” This general idea can be extended to an organicist framework in which collective rituals have self-maintenance functions and are necessary for the continual survival of the groups that engage in them. It is also compatible with a selectionist framework, such that groups engaging in socially cohesive rituals are capable of out-reproducing or (or assimilating) other less cohesive groups [@richerson_cultural_2016].

[^15]: The anthropologist Mary Douglas speculates that sociologists rely on the anthropological record because they find examples about rituals to be “quaint and entertaining” and that they are not really interested in engaging with anthropologists at all. “Elster attributes the Hopi Rain Dance to the Trobrianders, living in fertile, well-watered islands. We suspect that if he had attributed the Trobrianders’ ocean-fishing magic to the land-locked Hopi, it would not have mattered. The anthropology does not matter. It is not even interesting enough to be read. In this debate, it serves only as a stalking horse for more serious quarry, whatever that may be” [@douglas_how_1986, 43].

More contemporary research has tended to focus on providing answers to *how-does-it-work* questions about the way collective rituals produce social cohesion, leaving *why-is-it-there* questions about the “adaptive” nature of collective rituals to be adjudicated by more abstract discussions of “isolated causal mechanisms.” This has resulted in a more heterogeneous conception of collective rituals. Accordingly, rituals characterized by predictable, repetitive and rigid movements have been found to reduce anxiety among practitioners [@lang_role_2020]. Rituals involving some kind of “costly signaling” have been found to promote “group identification” among practitioners and to signal trustworthiness to other co-religionists [@lang_advertising_2022; @kantner_pilgrimage_2012]. Finally, rituals involving emotionally intense and memorable experiences (e.g., “rites of terror”) have been shown to alter the autobiographical self-concept of participants in a way that promotes a sort of tight integration among those who have these shared experiences. This last kind of ritual experience leads to a sort of “identity fusion” among participants, “binding them together as psychological kin and preparing them to participate in high risk activities such as hunting dangerous animals and going to war” [@whitehouse_ties_2014, 679].

Consider the example of ritual pilgrimages. These are long and costly journeys to sacred locations undertaken by individuals in search of goals that are hard to specify (e.g., spiritual transcendence or personal growth). Early accounts maintained that pilgrimages created “social cohesion” by breaking down the existing hierarchies of a group, putting practitioners on a level playing field, and engendering sentiments of “togetherness” which allowed for the reconciliation of social inequalities [@turner_image_1978]. This view was hard to square with what a lot of ethnographers observed on the ground. Instead of reconciliation, they found sites of “contestation” in which existing inequalities were often heightened and different conceptions of the sacred tended to clash with each other [@eade_contesting_1991]. In short, early accounts seeking to explain the existence of ritual pilgrimages by appealing to their “social cohesiveness” effects were met with little empirical support.

Part of the reason why these early accounts about pilgrimage proved insufficient is because the underlying mechanisms linking them to social cohesion were vaguely specified. In response, recent research has opted to sacrifice historical accuracy in exchange for causal transparency. An example of this broader effort is *costly signaling theory* [@bulbulia_signalling_2011; @brusse_signaling_2020]. The central premise is that pilgrimage may act as a reliable signal of commitment to group values and beliefs. This signal communicates trustworthiness and facilitates cooperation among members of the group. Importantly, this particular view of social cohesiveness has led to new empirical questions [e.g., @chvaja_religious_2023; @lang_advertising_2022; @kantner_pilgrimage_2012].

An alternative “isolated causal mechanism” is found in the theory of *credibility enhancing displays* [@henrich_evolution_2009]. This theory suggests that there might not be anything necessarily “adaptive” about the effects of pilgrimages and other costly endeavors. Instead, the argument is that people are more likely to imitate the beliefs and ritual practices of individuals who, in a manner of speaking, put their money where their mouth is. This imitation rule is adaptive because it allows people, on average, to avoid liars and manipulators (“actions speak louder than words”). This is also a potential explanation as to why the history of religions is filled with examples of sacrifice and martyrdom [@henrich_evolution_2009, 257]. In other words, the idea is that ritual pilgrimages are signals of religious sincerity and that people tend to imitate the behaviors of individuals holding sincere beliefs. In Henrich’s account it is the copying rule that has a proper function; the pilgrimage itself may turn out to be harmful, neutral, or adaptive.[^16]

[^16]: @henrich_evolution_2003 [253] does argue that credibility enhancing displays (CREDs) may contribute to the *differential reproduction* of any collective ritual that just so happens to create the grounds for greater military or economic performance in a broader context of group competition. These few collective rituals are then endowed with *proper functions* arising from a process of “cultural group selection” [@richerson_cultural_2016]. However, under these circumstances, it is hard to see CREDs as anything other than an extension of costly signaling theory [@brusse_signaling_2020].

# Discussion

Functionalism captured the hearts and minds of sociologists in the middle of the 20th century. It first emerged as the science of the “body social” and provided a distinctive means for thinking about societies as “organic wholes” that could then be analyzed in terms of the behavior of their interconnected “parts” [@turner_functionalism_1979]. This early organicist framework then elicited strong criticisms from many scholars who, unfortunately, did not care to salvage anything of value from the ensuing wreckage. Thus, sociologists learned to be skeptical of the word “function” in ways that are a hindrance for the development of sociological theory. However, we have argued that such skepticism is misguided and that various forms of functionalist argument do provide a kind of explanatory depth that is hard to obtain elsewhere. As Mary Douglas [-@douglas_how_1986, 43] once said, “for sociology to accept that no functionalist arguments work is like cutting off one’s nose to spite one’s face.”

Our discussion also provides reasons for finally abandoning the distinction between “manifest” and “latent” functions, which was originally used to adjudicate between surface-level appearances and the real causes hidden beneath them. There are very few social phenomena which can reasonably be labeled as latent—i.e., as having self-maintaining effects that are both unintended *and* unrecognized from the perspective of every first-person observer. Instead, we are better off distinguishing (1) phantom functions from (2) proper functions and role functions. Merton’s [-@merton_social_1968] concept of “manifest” function encompasses anything to which we can attribute a “subjective” intent. This includes all phantom functions but also a large number of proper functions and role functions. Similarly, his use of “latent” function encompasses various social phenomena with unintended, unrecognized, unanticipated, or undisclosed effects. But none of these terms are synonymous. Furthermore, their union is too all encompassing whereas their intersection is prohibitively narrow. As such, there was never anything of inherent value about the manifest-latent distinction.

In this paper we have attempted to remedy this situation by providing a framework that allows us to evaluate various kinds of functional ascription in which some X is described as having a function or serving a purpose. We started by embracing a pluralist stance towards functions [@garson_how_2018; @godfrey-smith_functions_1993]. Both *proper functions* (or “selected effects”) and *role functions* are central to the various forms of argument depicted in @fig-typology. We also distinguished between the two analytically distinct explanatory goals associated with each. The first seeks to provide answers to *why-is-it-there* questions and is thus *backward-looking* (or historic). The second seeks to provide answers to *how-does-it-work* questions and is thus *inward-looking* (and ahistoric). Our typology includes four plausible forms of functionalist argument that fit within this general framework. This framework supersedes the early organicist formulations of functionalist explanation along with the associated *self*-maintenance understanding of functions.

Our discussion also provides reasons for finally abandoning the distinction between “manifest” and “latent” functions, which was originally used to adjudicate between surface-level appearances and the real causes hidden beneath them. There are very few social phenomena which can reasonably be labeled as latent—i.e., as having self-maintaining effects that are both unintended *and* unrecognized from the perspective of every first-person observer. Instead, we are better off distinguishing (1) phantom functions from (2) proper functions and role functions. Merton’s (1968) concept of “manifest” function encompasses anything to which we can attribute a “subjective” intent. This includes all phantom functions but also a large number of proper functions and role functions. Similarly, his use of “latent” function encompasses various social phenomena with unintended, unrecognized, unanticipated, or undisclosed effects. But none of these terms are synonymous. More importantly, their union is too all encompassing whereas their intersection is prohibitively narrow. As such, there was never anything of inherent value about the manifest-latent distinction.

We are then left with four distinct plausible explanatory strategies. First, a functionalist argument can take the form of a concrete *history of selection* that explains why the function of some $X$ has led to its differential reproduction (or differential retention) over time. Second, it can take the form of an *isolated causal mechanism* that explains why some more abstract form of $X$ would have been selected for across a wide variety of circumstances. Both strategies are meant to answer *why-is-it-there* questions. The former prioritizes historical accuracy over causal transparency, whereas the latter does the exact opposite. Importantly, the meaning of the word “function” in these accounts corresponds to that of a proper function [@millikan_defense_1989; @garson_generalized_2017]. Third, a functionalist argument can take the form of an ahistorical *functional and mechanistic description* that explains some high-level feature of a “containing system” in terms of the organized activities of its component parts [@craver_search_2013]. The meaning of the word “function” in this account corresponds to that of a role function. Fourth, researchers might be interested in explaining a *goal-directed process* in which the target of inquiry is a special kind of behavior marked by persistence and plasticity [@nagel_goal-directed_1977; @mcshea_upper-directed_2012]. In this account, role functions are further qualified as being “goal-supporting.” Furthermore, many explanations of this sort rely on ideas about circular causality in the form of negative feedback loops [@rosenblueth_behavior_1943; @stinchcombe_constructing_1968; @robinson_control_2007].

Before concluding this article we point towards four areas of sociological inquiry that could benefit from engaging with the ideas discussed in this paper.

\noindent \textit{Circular causality}

The so-called credibility revolution in quantitative research is a much welcome development of the last few decades. However, the idea of circular causality cannot be easily accommodated within the framework of directed acyclic graphs and such questions are typically discouraged [@morgan_counterfactuals_2014: 80]. For example, mathematical and statistical models that account for the differential reproduction of behaviors over time are conspicuously absent from this literature. Crucially, negative feedback loops destroy the observed correlations between variables in a goal-directed process—i.e., any “homeostatic variable,” by definition, will exhibit little variation. In other words, even though recent developments in causal inference may have shed light upon various causal structures in the world, it is worth considering if perhaps we have reacted like the proverbial drunkard searching for his keys under the lamppost [cf. @stinchcombe_constructing_1968, 148].

\noindent \textit{Path dependence}

There is a lot of overlap between histories of selection and what historical sociologists typically describe as path-dependence. These arguments usually distinguish between (1) the particular circumstances or “critical juncture” that gives rise to some social phenomena and (2) the self-reinforcing process or “mechanism of reproduction” through which this social phenomena is kept stable over time [@stinchcombe_constructing_1968, 103; @mahoney_path_2000; @pierson_politics_2004]. It is a form of explanation that highlights the “frozen accidents” of history.

Following our earlier discussion, we might describe these “critical junctures” as historical episodes containing new “sources of variation,” perhaps the outcome of a deliberate process. Or we might describe them as moments in history in which existing social structures (perhaps the outcome of past episodes of selection) get co-opted for different purposes. The point is that there is nothing in our discussion of histories of selection that is incompatible with path-dependence arguments. The notion of proper function might thus be a welcome addition to the historical sociologist’s toolbox. The same goes for describing stable historical trajectories in terms of persistence and plasticity within the context of some goal-directed processes.

\noindent \textit{Neoinstitutionalism}

Sociologists call attention to various forms of *phantom functions* in discussions about organizational *decoupling*. This refers to organizations pursuing activities that are weakly linked or entirely disconnected from their official goals [@bromley_smoke_2012]. As @meyer_institutionalized_1977 [343] observed long ago,

> structural elements are only loosely linked to each other and to activities, rules are often violated, decisions are often unimplemented, or if implemented have uncertain consequences, technologies are of problematic efficiency, and evaluation and inspection systems are subverted or rendered so vague as to provide little coordination.

Neoinstitutionalists have argued that this provides evidence against “functionalism” in the sense that it contradicts a view of organizations as bounded and tightly-coupled social “systems” whose component parts are supportive of one another, much like the component parts of a living organism [@schneiberg_typical_2006]. But the concept of decoupling is not antithetical to all forms of “functionalism.” This becomes particularly clear in several instances when decoupling is described as a deliberate *avoidance strategy* against external accountability or legal liability. Such a view is also compatible with a power-based explanation according to which “decoupling is more common when it serves the interests of powerful leaders” [@bromley_smoke_2012, 493]. In other words, neoinstitutionalist scholars have presented themselves as being in opposition to survival-enhancing and self-maintenance understandings of functions. But their views are compatible with the broader view of functional ascription we present in @fig-typology.

\noindent \textit{Groups and Collective Goals}

Earlier we described persistence and plasticity as being the behavioral markers of goal-directed processes. But we had much less to say about goals themselves, other than the insistence that only humans and other living organisms have goals of their own. Nonetheless, sociologists still speak of various collectivities as if they were capable of having intentions and goals of their own. For example, we routinely speak of small teams as having collective goals. We describe entire categories of people as pursuing their own conflicting interests (e.g., workers and capitalists). And we tend to ascribe goals to coalitions, social movements, communities, and sometimes even to whole countries. In some cases, ascribing goals to these higher-level entities is merely a figure of speech in which the goals and intentions of some individual or spokesperson are taken to represent the larger whole. But sometimes it is more than that.

The extent to which a large collective of individuals can be usefully described as having “goals” is ultimately an empirical question. Whereas it is hard to attribute goals to crowds, it is much more reasonable to attribute goals to military units. The latter exhibits what @merton_social_1968 called “functional unity” and philosopher Samir Okasha [-@okasha_agents_2018] calls a “unity of purpose.” This means that, under some circumstances, the various component parts of some specific group or organization will contribute to a single overarching goal. In other words, while the structural-functionalists were wrong in attributing “needs” and “goals” to abstract macro-phenomena, they were right in pointing towards socialization and various mechanisms of social control (e.g., the imposition of risks and opportunities, punishments and rewards) as the main drivers of functional integration. There are numerous problems of collective action that must be solved first in order for a group to exhibit a “unity of purpose.”

# Conclusion

We maintain that many of the impassioned and confusing discussions among sociologists regarding the validity of functionalist arguments can be peacefully resolved within this plural framework. These forms of argument are generic. They do not come with any built-in substantive or normative view about society.[^17] Moreover, there is no reason why one should label any substantive theory that makes use of such arguments as a functional*ist* theory. In the same way that we do not refer to substantive theories that make use of logical syllogisms as logic*ist* theories. On the contrary, we argue that “functionalism” as an all encompassing term is troublesome. It encourages confusion because it conflates various forms of argument, each with its own explanatory goals and evidentiary thresholds. Our framework is meant to be a tool that helps us identify, evaluate, challenge, and improve upon much of the sociological research that currently relies on these types of arguments.

[^17]: Importantly, even though there is no built-in normative stance in our four forms of functionalist argument, the opposite is not necessarily true. In fact, it is hard to imagine any form of critical scholarship or social movement that manages to steer clear from ideas about goals and functions.

\newpage

# References {.unnumbered .unlisted}
